POST http://192.168.0.102:8000/measurements/
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|QB7zzoapJqZr88YUsc9arxoLnXU6uuA3Uv4afZdW913c778b

{
    "sensor": "soil_temperature",
    "value": 150
}

# GET http://localhost:8000/api/measurements?sensor=soil_temperature&start=2024-02-24%2018:00:00
# Content-Type: application/json
# Accept: application/json
# Authorization: Bearer 2|RdE2mBRZagiuSnANh3pIdgLI5cNoxl2BeCyrEWtv50a70c87